config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/999000bank000999'
  # resources :requests
  resources :calls do
    post :add_formulator, on: :member
    post :add_pertinency_reviewer, on: :member
    post :add_format_reviewer, on: :member
    post :switch_status, on: :member
    post 'edit_formulator_categories/:user_call_id', to: 'calls#edit_formulator_categories', as: 'edit_formulator_categories'
  end
  # resources :candidates
  resources :acceptance_processes
  # resources :category_specialities
  # resources :alternatives
  get 'categories/list', action: :list, controller: 'categories'
  get 'categories/edit_tree', action: :edit_tree, controller: 'categories'
  resources :categories, except: %i[edit show new]
  # resources :users_specialities
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }

  # resources :question_tracks
  # resources :specialities
  # resources :role_permissions
  # resources :permissions
  resources :entrance_exams do
    post 'add_question/:question_id', to: 'entrance_exams#add_question', as: 'add_question_to_entrance_exam'
    delete 'remove_question/:question_id', to: 'entrance_exams#remove_question', as: 'remove_question_from_entrance_exam'
  end

  get 'tags/:tag', to: 'questions#index_formulator', as: :tag
  get '/questions/index_operator', to: 'questions#index_operator'
  get '/questions/index_formulator', to: 'questions#index_formulator'
  get '/questions/index_reviewer', to: 'questions#index_reviewer'
  get '/questions/edit_formulator', to: 'questions#edit_formulator', as: 'question_formulator'
  get '/questions/edit_reviewer', to: 'questions#edit_reviewer', as: 'edit_reviewer'
  get '/questions/formulator_status', to: 'questions#formulator_status', as: 'formulator_status'
  get '/questions/reviewer_status', to: 'questions#reviewer_status', as: 'reviewer_status'
  resources :questions do
    resources :comments, only: %i[index show create update destroy]
    post :assign_question, on: :member
    post :approve_question, on: :member
    post :reject_question, on: :member
    post :send_question_to_review, on: :member
    post :observe_question, on: :member
  end
  get '/users/pertinency_reviewers', to: 'users#pertinency_reviewers'
  get '/users/format_reviewers', to: 'users#format_reviewers'
  resources :users do
    patch :update_password, on: :member
    get :password_edit, on: :member
  end
  resources :roles
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/call.rb
# frozen_string_literal: true

class Call < ApplicationRecord
  validates :name, presence: true, length: { in: 1..50 }
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  has_many :user_calls
  has_many :users, through: :user_calls

  enum status: { inactive: 0, active: 1 }

  before_create :set_status
  # after_create :create_jobs
  # after_update :update_jobs
  # after_destroy :delete_jobs

  def set_status
    self.status = 'inactive'
  end

  def delete_start_job
    Sidekiq::ScheduledSet.new.find_job(start_jid).delete
  end

  def delete_end_job
    Sidekiq::ScheduledSet.new.find_job(end_jid).delete
  end

  def create_jobs
    start_jid = StartCallWorker.perform_at(starts_at, id)
    end_jid = EndCallWorker.perform_at(ends_at, id)
    update(start_jid: start_jid, end_jid: end_jid)
  end

  def update_jobs
    if starts_at_changed?
      delete_start_job
      self.start_jid = StartCallWorker.perform_at(starts_at, id)
    end

    if ends_at_changed?
      delete_end_job
      self.end_jid = EndCallWorker.perform_at(ends_at, id)
    end
  end

  def delete_jobs
    delete_start_job
    delete_end_job
  end
end

app/models/user_call.rb
# frozen_string_literal: true

class UserCall < ApplicationRecord
  belongs_to :user
  belongs_to :call
  has_many :user_call_categories
  has_many :categories, through: :user_call_categories
  has_many :user_call_questions
  has_many :questions, through: :user_call_questions

  validates_uniqueness_of :user_id, scope: :call_id
end

app/controllers/calls_controller.rb
# frozen_string_literal: true

##
# Gestión de Convocatorias.

class CallsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_call, only: %i[show edit update destroy add_formulator add_pertinency_reviewer add_format_reviewer switch_status]
  before_action :connect_redis, only: %i[add_formulator add_pertinency_reviewer add_format_reviewer switch_status]

  require 'redis'

  # GET /calls
  # GET /calls.json

  ##
  # Retorna la lista de convocatorias.
  def index
    @calls = Call.all
    authorize @calls
  end

  # GET /calls/1
  # GET /calls/1.json

  ##
  # Redirige a la vista de agregación de usuarios para una convocatoria.
  def show
    authorize @call
    formulator_ids = UserPermission.where(permission_name: 'complex_formulator_permission').pluck(:user_id)
    pertinency_reviewer_ids = UserPermission.where(permission_name: 'complex_pertinency_reviewer_permission').pluck(:user_id)
    format_reviewer_ids = UserPermission.where(permission_name: 'complex_format_reviewer_permission').pluck(:user_id)

    @current_formulators_ids = @call.user_calls.where(user_id: formulator_ids).includes(:user)
    @current_pertinency_reviewers_ids = @call.user_calls.where(user_id: pertinency_reviewer_ids).includes(:user)
    @current_format_reviewers_ids = @call.user_calls.where(user_id: format_reviewer_ids).includes(:user)

    ids = formulator_ids - @current_formulators_ids.pluck(:user_id)
    @formulators = User.find(ids)

    remaining_pertinency_reviewers_ids = pertinency_reviewer_ids - @current_pertinency_reviewers_ids.pluck(:user_id)
    @remaining_pertinency_reviewers = User.find(remaining_pertinency_reviewers_ids)

    remaining_format_reviewers_ids = format_reviewer_ids - @current_format_reviewers_ids.pluck(:user_id)
    @remaining_format_reviewers = User.find(remaining_format_reviewers_ids)
    # Falta elegir bien las categorias
    @categories = Category.where(is_leaf: true)
  end

  # GET /calls/new

  ##
  # Redirige a la vista de nueva convocatoria.
  def new
    @call = Call.new
    authorize @call
  end

  # GET /calls/1/edit

  ##
  # Retorna la edición de convocatorias.
  def edit
    authorize @call
  end

  # POST /calls
  # POST /calls.json

  ##
  # Crea una nueva convocatoria.
  def create
    @call = Call.new(call_params)
    authorize @call

    respond_to do |format|
      if @call.starts_at > @call.ends_at
        format.html { redirect_to request.referer, alert: 'No puede existir fecha de inicio posterior a la de fin' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      elsif @call.save
        format.html { redirect_to calls_path, notice: 'El proceso de formulación se creó correctamente.' }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1
  # PATCH/PUT /calls/1.json

  ##
  # Actualiza una convocatoria.
  def update
    authorize @call
    respond_to do |format|
      if call_params['starts_at'] > call_params['ends_at']
        format.html { redirect_to request.referer, alert: 'No puede existir fecha de inicio posterior a la de fin' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      elsif @call.update(call_params)
        format.html { redirect_to @call, notice: 'El proceso de formulación se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Agrega un formulador a una convocatoria.
  def add_formulator
    authorize @call
    formulator_id = params[:call][:formulator_id]
    category_ids = params[:call][:category_ids] - ['']
    if formulator_id.blank? || category_ids.blank?
      respond_to do |format|
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
      return
    end

    formulator = User.find(params[:call][:formulator_id])
    categories = Category.where(id: (params[:call][:category_ids]), is_leaf: true)

    user_call = UserCall.new
    user_call.user_id = formulator.id
    user_call.call_id = @call.id
    user_call.biomedical_questions_limit = params[:call][:biomedical_questions_limit]
    user_call.social_questions_limit = params[:call][:social_questions_limit]
    user_call.engineering_questions_limit = params[:call][:engineering_questions_limit]

    respond_to do |format|
      if user_call.save
        user_call.categories << categories
        @redis.rpush 'formulation_process_formulators', formulator.id if formulator.id
        FormulatorMailer.with(formulator_id: formulator.id, call_id: @call.id, user_call_id: user_call.id).summon_formulator_email.deliver_later
        format.html { redirect_to call_path(@call), notice: 'El proceso de formulación se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Agrega un revisor de pertinencia a una convocatoria.
  def add_pertinency_reviewer
    authorize @call
    pertinency_reviewer_id = params[:call][:pertinency_reviewer_id]
    if pertinency_reviewer_id.blank?
      respond_to do |format|
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
      return
    end

    pertinency_reviewer = User.find(params[:call][:pertinency_reviewer_id])

    user_call = UserCall.new
    user_call.user_id = pertinency_reviewer.id
    user_call.call_id = @call.id

    respond_to do |format|
      if user_call.save
        @redis.rpush 'formulation_process_pertinency_reviewers', pertinency_reviewer.id if pertinency_reviewer.id
        format.html { redirect_to call_path(@call), notice: 'El revisor de pertinencia se añádió correctamente.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Agrega un revisor de estilo a una convocatoria.
  def add_format_reviewer
    authorize @call
    format_reviewer_id = params[:call][:format_reviewer_id]
    if format_reviewer_id.blank?
      respond_to do |format|
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
      return
    end

    format_reviewer = User.find(params[:call][:format_reviewer_id])

    user_call = UserCall.new
    user_call.user_id = format_reviewer.id
    user_call.call_id = @call.id

    respond_to do |format|
      if user_call.save
        @redis.rpush 'formulation_process_format_reviewers', format_reviewer.id if format_reviewer.id
        format.html { redirect_to call_path(@call), notice: 'El revisor de pertinencia se añádió correctamente.' }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { redirect_to call_path(@call), alert: 'Something went wrong.' }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json

  def destroy
    authorize @call
    @call.destroy
    respond_to do |format|
      format.html { redirect_to calls_url, notice: 'El proceso de formulación se eliminó con éxito.' }
      format.json { head :no_content }
    end
  end

  ##
  # Cambia es estado de una convocatoria, solo puede existir una convocatoria activa.
  def switch_status
    authorize @call
    formulator_ids = UserPermission.where(permission_name: 'complex_formulator_permission').pluck(:user_id)
    pertinency_reviewer_ids = UserPermission.where(permission_name: 'complex_pertinency_reviewer_permission').pluck(:user_id)
    format_reviewer_ids = UserPermission.where(permission_name: 'complex_format_reviewer_permission').pluck(:user_id)

    active_calls = Call.where(status: 'active')
    current_formulators = @call.user_calls.where(user_id: formulator_ids).pluck(:user_id)
    current_pertinency_reviewers = @call.user_calls.where(user_id: pertinency_reviewer_ids).pluck(:user_id)
    current_format_reviewers = @call.user_calls.where(user_id: format_reviewer_ids).pluck(:user_id)
    if @call.status == 'inactive' && active_calls.empty?
      @call.status = 'active'
      @redis.set 'is_formulation_process_active', true
      @redis.rpush 'formulation_process_formulators', current_formulators unless current_formulators.empty?
      @redis.rpush 'formulation_process_pertinency_reviewers', current_pertinency_reviewers unless current_pertinency_reviewers.empty?
      @redis.rpush 'formulation_process_format_reviewers', current_format_reviewers unless current_format_reviewers.empty?
    elsif @call.status == 'active'
      @call.status = 'inactive'
      active_calls = []
      @redis.del 'is_formulation_process_active'
      @redis.del 'formulation_process_formulators'
      @redis.del 'formulation_process_pertinency_reviewers'
      @redis.del 'formulation_process_format_reviewers'
    end

    respond_to do |format|
      if active_calls.empty?
        if @call.save
          format.html { redirect_to calls_url, notice: 'El proceso de formulación se actualizó correctamente.' }
          format.json { render json: { message: 'El proceso de formulación se actualizó correctamente.' }, status: :ok }
        else

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_active_modal.html.haml
/ Start modal part
.modal.fade{id: "activeModal-#{object.id}", tabindex: "-1", role: "dialog", "aria-labelledby": "exampleModalLabel", "aria-hidden": "true"}
  .modal-dialog{role: "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title 
          %b= object.active? ? "Desactivar Convocatoria" : "Activar Convocatoria"
        %button.close{"aria-label": "Close", "data-dismiss": "modal", type: "button"}
          %span{"aria-hidden": "true"} ×
      .modal-body
        = message
      .modal-footer
        = link_to 'Aceptar', switch_status_call_path(object), method: :post, class: "btn btn-primary"
        %button.btn.btn-secondary{"data-dismiss": "modal", type: "button"} Cancelar
/ End modal part

app/views/calls/_add_format_reviewers.html.haml
.form-content
  %h3.pl-4.mb-3 Agregar Revisores de Estilo
  = form_with url: add_format_reviewer_call_path(call), scope: 'call', local: true, class: "form-inline mb-3" do |form|
    .row
      .col-md-3.col-sm12
        = form.collection_select :format_reviewer_id, format_reviewers, :id, :full_name, { prompt: 'Elija al Revisor de Estilo' }, {required: true}

    %button.btn.btn-primary{:type => "submit"} Agregar

  .table-responsive
    %table.table.table-striped.table-bordered
      %thead{:align => "center"}
        %tr
          %th 
            %a ID
          %th 
            %a Nombre
      %tbody
        - @current_format_reviewers_ids.each do |user_call|
          %tr
            %td= user_call.user.id
            %td= user_call.user.full_name

app/views/calls/_add_pertinency_reviewers.html.haml
.form-content
  %h3.pl-4.mb-3 Agregar Revisores de Pertinencia
  = form_with url: add_pertinency_reviewer_call_path(call), scope: 'call', local: true, class: "form-inline mb-3" do |form|
    .row
      .col-md-3.col-sm12
        = form.collection_select :pertinency_reviewer_id, pertinency_reviewers, :id, :full_name, { prompt: 'Elija al Revisor de Pertinencia' }, {required: true}

    %button.btn.btn-primary{:type => "submit"} Agregar

  .table-responsive
    %table.table.table-striped.table-bordered
      %thead{:align => "center"}
        %tr
          %th 
            %a ID
          %th 
            %a Nombre
      %tbody
        - @current_pertinency_reviewers_ids.each do |user_call|
          %tr
            %td= user_call.user.id
            %td= user_call.user.full_name

app/views/calls/_add_users.html.haml
.form-content
  %h3.pl-4.mb-3 Agregar Formuladores
  = form_with url: add_formulator_call_path(call), scope: 'call', local: true, class: "form-inline mb-3" do |form|
    .row.col-sm-12.mb-3
      .col-lg-4.col-sm-12
        = form.collection_select :formulator_id, formulators, :id, :full_name, { prompt: 'Elija al Formulador' }, {required: true}
      .col-lg-4.col-sm-12
        = form.collection_select :category_ids, categories, :id, :name, { prompt: 'Seleccionar Categorias' }, { multiple: true, class: 'form-control', required: true }
      .col-lg-1.col-sm-12
        = form.label :'Preguntas Biomédicas:'
        = form.text_field :biomedical_questions_limit, maxlength: "3", class: "form-control", :required => true
      .col-lg-1.col-sm-12
        = form.label :'Preguntas Sociales:'
        = form.text_field :social_questions_limit, maxlength: "3", class: "form-control", :required => true
      .col-lg-1.col-sm-12
        = form.label :'Preguntas Ingenierias:'
        = form.text_field :engineering_questions_limit, maxlength: "3", class: "form-control", :required => true
      .col-lg-1.col-sm-12
        %button.btn.btn-primary{:type => "submit"} Agregar
    
    .row.col-sm-8
      
  .table-responsive
    %table.table.table-striped.table-bordered
      %thead{:align => "center"}
        %tr
          %th 
            %a ID
          %th 
            %a Nombre
          %th{col: '4'} 
            %a Categorias
          %th
            %a Límite Preguntas Biomédicas
          %th
            %a Límite Preguntas Sociales
          %th
            %a Límite Preguntas Ingenierias
          %th
            %a Acciones
      %tbody
        - @current_formulators_ids.each do |user_call|
          %tr
            %td= user_call.user.id
            %td= user_call.user.full_name
            %td= user_call.categories.pluck(:name).join(', ')
            %td= user_call.biomedical_questions_limit
            %td= user_call.social_questions_limit
            %td= user_call.engineering_questions_limit
            %td
              = link_to '#', data: {target: '#modalEditCategoriesForm', toggle: 'modal', categories: user_call.categories.ids.join(','), name: user_call.user.full_name, user_call_id: user_call.id, call_id: call.id } do
                %span.btn.btn-link{class: "material-icons", style: "vertical-align: middle; color:black;" } edit

  = render 'edit_formulator_categories', categories: categories, call: call

app/views/calls/_edit_formulator_categories.html.haml
:javascript
  $(document).on('turbolinks:load', function(){
    
  });


#modalEditCategoriesForm.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header.text-center.mb-4
        %h5#user-name.modal-title.w-100.font-weight-bold
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body.mx-3
        = form_with url: '#', method: :post, scope: 'user_call', local: true, class: "md-form mb-5", id: 'user_call_form' do |form|
          .row.col-s12
            %h5 Categorias
            = form.collection_select :category_ids, categories, :id, :name, { prompt: 'Seleccionar Categorias' }, { multiple: true, class: 'form-control', required: true }
            = form.submit 'Guardar', class: "btn btn-primary mt-4 w-100"

app/views/calls/_form.html.haml
.form-content
  = form_with(model: call, local: true, class: 'question-form', id: 'question-form', html: {novalidate: true }) do |form|
    - if call.errors.any?
      #error_explanation
        %h2
          = pluralize(call.errors.count, "error")
          prohibited this call from being saved:
        %ul
          - call.errors.full_messages.each do |message|
            %li= message
    .form-group
      = form.label :'Nombre', style: "font-weight: bold"
      = form.text_field :name, maxlength: "50", class: "form-control", :required => true
      .invalid-feedback
        Campo obligatorio

    .form-group
      = form.label :'Inicia'
      = form.date_field :starts_at, class: "form-control", :required => true
      .invalid-feedback
        Campo obligatorio
        
    .form-group
      = form.label :'Termina'
      = form.date_field :ends_at, class: "form-control", :required => true                                              |
      .invalid-feedback
        Campo obligatorio
    .actions{style: "float: right"}
      = form.submit 'Guardar', class: "btn btn-primary"
      = link_to 'Cancelar', calls_path, class: "btn btn-dark"

app/views/calls/edit.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Editar Convocatoria

= render 'form', call: @call

app/views/calls/index.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Convocatorias
    .col-md-6.d-flex.right-panel
      = link_to new_call_path, data: {turbolinks: false}, class: "btn btn-primary add-button" do
        %span{class: "material-icons"} add
        Nueva Convocatoria

  .table-responsive
    %table#pagination.table.table-striped.table-bordered
      %thead{:align => "center"}
        %tr
          %th 
            %a ID
          %th 
            %a Nombre
          %th 
            %a Inicio
          %th 
            %a Fin
          %th 
            %a Estado
          %th{col: "2"}
            %a Acciones
      %tbody
        - @calls.each do |call|
          %tr
            %td= call.id
            %td= link_to call.name, call_path(call)
            %td= call.starts_at.strftime("%B %d, %Y %A")
            %td= call.ends_at.strftime("%B %d, %Y %A")
            %td{:align => "center"}
              %a.btn.btn-link{"data-todo" => {"id": "#{call.id}"}, "data-toggle": "modal", href: "#activeModal-#{call.id}"}
                %span.material-icons{style: "vertical-align: middle;", class: call.active? ? 'text-success' : 'text-danger'}= call.active? ? 'flash_on' : 'flash_off'
            = render '/calls/active_modal', object: call, message: "Estás seguro que quieres #{call.active? ? 'inactivar' : 'activar'} esta convocatoria?"
    
            %td
              = link_to call_path(call) do
                %span.material-icons{style: "vertical-align: middle;"} playlist_add
                Agregar Formuladores
            = render '/layouts/show_modal'

app/views/calls/new.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Nueva Convocatoria

= render 'form', call: @call

app/views/calls/show.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b= @call.name
    .col-md-6.d-flex.right-panel
      = link_to 'Regresar', calls_path, class: "btn btn-primary add-button mr-2"
      = link_to edit_call_path(@call), data: {turbolinks: false}, class: "btn btn-primary add-button" do
        %span{class: "material-icons"} edit
        Editar Convocatoria

.form-content
  .card
    .card-body
      %strong Nombre:
      = "#{@call.name}"
  
  .card
    .card-body
      %strong Fecha de Inicio:
      = @call.starts_at.strftime("%B %d, %Y %A")
  
  .card
    .card-body
      %strong Fecha de Término
      = @call.ends_at.strftime("%B %d, %Y %A")
%hr
= render 'add_users', call: @call, formulators: @formulators, categories: @categories

%hr
= render 'add_pertinency_reviewers', call: @call, pertinency_reviewers: @remaining_pertinency_reviewers

%hr
= render 'add_format_reviewers', call: @call, format_reviewers: @remaining_format_reviewers