config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/999000bank000999'
  # resources :requests
  resources :calls do
    post :add_formulator, on: :member
    post :add_pertinency_reviewer, on: :member
    post :add_format_reviewer, on: :member
    post :switch_status, on: :member
    post 'edit_formulator_categories/:user_call_id', to: 'calls#edit_formulator_categories', as: 'edit_formulator_categories'
  end
  # resources :candidates
  resources :acceptance_processes
  # resources :category_specialities
  # resources :alternatives
  get 'categories/list', action: :list, controller: 'categories'
  get 'categories/edit_tree', action: :edit_tree, controller: 'categories'
  resources :categories, except: %i[edit show new]
  # resources :users_specialities
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }

  # resources :question_tracks
  # resources :specialities
  # resources :role_permissions
  # resources :permissions
  resources :entrance_exams do
    post 'add_question/:question_id', to: 'entrance_exams#add_question', as: 'add_question_to_entrance_exam'
    delete 'remove_question/:question_id', to: 'entrance_exams#remove_question', as: 'remove_question_from_entrance_exam'
  end

  get 'tags/:tag', to: 'questions#index_formulator', as: :tag
  get '/questions/index_operator', to: 'questions#index_operator'
  get '/questions/index_formulator', to: 'questions#index_formulator'
  get '/questions/index_reviewer', to: 'questions#index_reviewer'
  get '/questions/edit_formulator', to: 'questions#edit_formulator', as: 'question_formulator'
  get '/questions/edit_reviewer', to: 'questions#edit_reviewer', as: 'edit_reviewer'
  get '/questions/formulator_status', to: 'questions#formulator_status', as: 'formulator_status'
  get '/questions/reviewer_status', to: 'questions#reviewer_status', as: 'reviewer_status'
  resources :questions do
    resources :comments, only: %i[index show create update destroy]
    post :assign_question, on: :member
    post :approve_question, on: :member
    post :reject_question, on: :member
    post :send_question_to_review, on: :member
    post :observe_question, on: :member
  end
  get '/users/pertinency_reviewers', to: 'users#pertinency_reviewers'
  get '/users/format_reviewers', to: 'users#format_reviewers'
  resources :users do
    patch :update_password, on: :member
    get :password_edit, on: :member
  end
  resources :roles
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/entrance_exam.rb
# frozen_string_literal: true

class EntranceExam < ApplicationRecord
  has_many :question_entrance_exams
  has_many :questions, through: :question_entrance_exams
end

app/controllers/entrance_exams_controller.rb
# frozen_string_literal: true

##
# Gestión de Exámenes.
class EntranceExamsController < ApplicationController
  before_action :authenticate_user!
  # before_action :verify_formulation_process, except: %i[formulator_status reviewer_status]
  # before_action :check_questions_limit, only: %i[new create]
  before_action :set_entrance_exam, only: %i[show edit update destroy]
  # skip_before_action :verify_authenticity_token, only: [:assign_question]
  # before_action :set_paper_trail_whodunnit

  # GET /questions
  # GET /questions.json
  ##
  # Retorna la lista de exámenes.
  def index
    @entrance_exams = EntranceExam.all
    authorize @entrance_exams
  end

  # GET /questions/1
  # GET /questions/1.json
  ##
  # Redirige a la vista de agregación de preguntas para un exámen.
  def show
    authorize @entrance_exam
    # @q = Question.ransack(params[:q])
    # @questions = @q.result(distinct: true)
    ids = @entrance_exam.question_entrance_exams.pluck(:question_id)
    @questions = Question.where.not(id: ids).where(status: APPROVED).includes(:category).order(:created_at)
    @added_questions = Question.where(id: ids).includes(:category).order(:created_at)
  end

  # GET /questions/new
  ##
  # Redirige a la vista de creación de un nuevo exámen.
  def new
    @entrance_exam = EntranceExam.new
    authorize @entrance_exam
  end

  # GET /questions/1/edit
  def edit
    authorize @entrance_exam
  end

  # POST /questions
  # POST /questions.json
  ##
  # Crea un nuevo exámen.
  def create
    @entrance_exam = EntranceExam.new(entrance_exam_params)
    authorize @entrance_exam
    if @entrance_exam.save
      respond_to do |format|
        format.html { redirect_to entrance_exams_path, notice: 'Exámen de entrada creado exitosamente.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to entrance_exams_path, alert: 'El exámen no pudo ser creado.' }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    authorize @entrance_exam
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    authorize @entrance_exam

    unless @entrance_exam.incomplete?
      respond_to do |format|
        format.html { redirect_to questions_index_formulator_path, alert: 'La pregunta está en revisión. No se puede eliminar' }
      end
      return
    end

    if @entrance_exam.destroy
      respond_to do |format|
        format.html { redirect_to questions_index_formulator_path, notice: 'La pregunta fue eliminada exitósamente' }
      end
    else
      respond_to do |format|
        format.html { redirect_to questions_index_formulator_path, alert: 'No se pudo eliminar la pregunta' }
      end
    end
  end

  ##
  # Agrega una pregunta aprovada a un exámen.
  def add_question
    entrance_exam = EntranceExam.find(params[:entrance_exam_id])
    authorize entrance_exam
    # if @entrance_exam.pertinency_approved_at.blank? &&  @entrance_exam.format_approved_at.blank?
    # reviewer.role.permissions.
    question = Question.find(params[:question_id])
    question_entrance_exam = QuestionEntranceExam.new(question_id: question.id, entrance_exam_id: entrance_exam.id)
    if question_entrance_exam.save
      respond_to do |format|
        format.html { redirect_to entrance_exam_path(entrance_exam), notice: 'Pregunta agregada exitosamente.' }
        format.json { render json: { message: 'Agregado Exitosamente' }.to_json, status: :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to entrance_exams_path(entrance_exam), notice: 'No se pudo agregar pregunta.' }
        format.json { render json: { error: 'Algo salió mal.' }.to_json, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Quita una pregunta aprovada de un exámen.
  def remove_question
    entrance_exam = EntranceExam.find(params[:entrance_exam_id])
    authorize entrance_exam
    question = Question.find(params[:question_id])
    entrance_exam_question = QuestionEntranceExam.where(question_id: question.id, entrance_exam_id: entrance_exam.id).first
    if entrance_exam_question.destroy
      respond_to do |format|
        format.html { redirect_to entrance_exams_path, notice: 'Pregunta quitada exitosamente.' }
        format.json { render json: { message: 'Quitado Exitosamente' }.to_json, status: :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to entrance_exams_path, notice: 'No se pudo quitar pregunta.' }
        format.json { render json: { error: 'Algo salió mal.' }.to_json, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entrance_exam
    @entrance_exam = EntranceExam.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entrance_exam_params
    params.require(:entrance_exam).permit(:name, :description, :tooked_at)
  end
end

app/views/entrance_exams/_add_questions.html.haml
= render 'add_questions_form', entrance_exam: @entrance_exam

.table-responsive
  %table#pagination.table.table-striped.table-bordered
    %thead{:align => "center"}
      %tr
        %th 
          %a ID
        %th 
          %a Categoría
        %th 
          %a Creación
        %th 
          %a Aprobación Pertinencia
        %th 
          %a Aprobación Estilo
        %th 
          %a Detalle
        %th 
          %a Estado
        %th
          %a Opciones
    %tbody
      - @added_questions.each do |question|
        %tr
          %td{:align => "center"}= question.id
          %td{:align => "center"}= question.category.name
          %td{:align => "center"}= question.created_at
          %td{:align => "center"}= question.pertinency_approved_at
          %td{:align => "center"}= question.format_approved_at
          %td
            %a.btn.btn-dark{"data-todo" => {"id": "#{question.id}"}, "data-toggle": "modal", href: "#previewShowModal-#{question.id}"}
              %span.material-icons{style: "vertical-align: middle;"} visibility
          %td= question.status
          %td= link_to 'Quitar Pregunta', entrance_exam_remove_question_from_entrance_exam_path(@entrance_exam, question), method: :delete, data: { confirm: 'Seguro que quieres quitar esta pregunta ?' }
          = render '/questions/question_preview_modal_added', object: question

app/views/entrance_exams/_add_questions_form.haml
:javascript
  $(document).on("turbolinks:load", function () {
    console.log('causa')
    $('#close-questions-modal').on('click', function() {
      $('#exam_questions_modal').modal('hide');
    });
  })
  
/ Large modal

#exam_questions_modal.modal.fade.bd-example-modal-lg{style: "width: 100%", "aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-xl
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Banco de Preguntas
        %button.close#close-questions-modal{"aria-label" => "Close", "data-dismiss" => "modal", :type => 'button'}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        .table-responsive
          %table#pagination.table.table-striped.table-bordered
            %thead{:align => "center"}
              %tr
                %th 
                  %a ID
                %th 
                  %a Categoría
                %th 
                  %a Creación
                %th 
                  %a Aprobación Pertinencia
                %th 
                  %a Aprobación Estilo
                %th 
                  %a Detalle
                %th 
                  %a Estado
                %th
                  %a Opciones
            %tbody
              - @questions.each do |question|
                %tr
                  %td{:align => "center"}= question.id
                  %td{:align => "center"}= question.category.name
                  %td{:align => "center"}= question.created_at
                  %td{:align => "center"}= question.pertinency_approved_at
                  %td{:align => "center"}= question.format_approved_at
                  %td
                    %a.btn.btn-dark{"data-todo" => {"id": "#{question.id}"}, "data-toggle": "modal", href: "#showModal-#{question.id}"}
                      %span.material-icons{style: "vertical-align: middle;"} visibility
                  %td= question.status
                  %td= link_to 'Añadir Pregunta', entrance_exam_add_question_to_entrance_exam_path(entrance_exam, question), method: :post, data: { confirm: 'Seguro que quieres agregar esta pregunta ?' }
                  = render '/questions/question_preview_modal', object: question

      //.modal-footer
      //  %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
      //  %button.btn.btn-primary{:type => "button"} Send message

app/views/entrance_exams/_form.html.haml
.form-content
  = form_with(model: entrance_exam, local: true, class: 'entrance-exam-form', id: 'entrance-exam-form', html: {novalidate: true }) do |form|
    - if entrance_exam.errors.any?
      #error_explanation
        %h2
          = pluralize(entrance_exam.errors.count, "error")
          prohibited this entrance exam from being saved:
        %ul
          - entrance_exam.errors.full_messages.each do |message|
            %li= message
    .form-group
      = form.label :'Nombre', style: "font-weight: bold"
      = form.text_field :name, maxlength: "50", class: "form-control", :required => true
      .invalid-feedback
        Campo obligatorio

    .form-group
      = form.label :'Descripción', style: "font-weight: bold"
      = form.text_area :description, class: "form-control", :required => false
      .invalid-feedback
        Campo obligatorio

    .form-group
      = form.label :'Fecha de Exámen'
      = form.date_field :tooked_at, class: "form-control", :required => true
      .invalid-feedback
        Campo obligatorio
        
    .actions{style: "float: right"}
      = form.submit 'Guardar', class: "btn btn-primary", data: {turbolinks: false}
      = link_to 'Cancelar', entrance_exams_path, class: "btn btn-dark"

app/views/entrance_exams/index.html.haml
/ Operator index, include policies for view
/ Operator index, include policies for view
.container-questions
  %div
  .row
    %div
    .col-md-6
      %h2
        %b Exámenes de Admisión
    .col-md-6.d-flex.right-panel
      = link_to new_entrance_exam_path, data: {turbolinks: false}, class: "btn btn-primary add-button" do
        %span{class: "material-icons"} add
        Nuevo Exámen

  %br/
  .table-responsive
    %table#pagination.table.table-striped.table-bordered
      %thead{:align => "center"}
        %tr
          %th 
            %a ID
          %th 
            %a Nombre
          %th 
            %a Descripción
          %th 
            %a Fecha de Exámen
          %th 
            %a Fecha de Definición
          %th{col: "2"}
            %a Acciones
      %tbody
        - @entrance_exams.each do |entrance_exam|
          %tr
            %td{:align => "center"}= entrance_exam.id
            %td{:align => "center"}= entrance_exam.name
            %td{:align => "center"}= entrance_exam.description
            %td{:align => "center"}= entrance_exam.tooked_at
            %td{:align => "center"}= entrance_exam.defined_at
            %td
              = link_to entrance_exam_path(entrance_exam) do
                %span.material-icons{style: "vertical-align: middle;"} playlist_add
                Agregar Preguntas

app/views/entrance_exams/new.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Nuevo Exámen

= render 'form', entrance_exam: @entrance_exam

app/views/entrance_exams/show.html.haml
.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b= @entrance_exam.name
    .col-md-6.d-flex.right-panel
      = link_to 'Regresar', entrance_exams_path, class: "btn btn-primary add-button mr-2"
      = link_to edit_entrance_exam_path(@entrance_exam), data: {turbolinks: false}, class: "btn btn-primary add-button" do
        %span{class: "material-icons"} edit
        Editar Datos de Exámen

.form-content
  .card
    .card-body
      %strong Nombre:
      = "#{@entrance_exam.name}"
  
  .card
    .card-body
      %strong Fecha de Exámen:
      = @entrance_exam.tooked_at.strftime("%B %d, %Y %A")

%button.btn.btn-primary{"data-target" => ".bd-example-modal-lg", "data-toggle" => "modal", :type => "button"} Elegir Preguntas

= render 'add_questions'
  