config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/999000bank000999'
  # resources :requests
  resources :calls do
    post :add_formulator, on: :member
    post :add_pertinency_reviewer, on: :member
    post :add_format_reviewer, on: :member
    post :switch_status, on: :member
    post 'edit_formulator_categories/:user_call_id', to: 'calls#edit_formulator_categories', as: 'edit_formulator_categories'
  end
  # resources :candidates
  resources :acceptance_processes
  # resources :category_specialities
  # resources :alternatives
  get 'categories/list', action: :list, controller: 'categories'
  get 'categories/edit_tree', action: :edit_tree, controller: 'categories'
  resources :categories, except: %i[edit show new]
  # resources :users_specialities
  devise_for :users, controllers: { sessions: 'users/sessions', passwords: 'users/passwords' }

  # resources :question_tracks
  # resources :specialities
  # resources :role_permissions
  # resources :permissions
  resources :entrance_exams do
    post 'add_question/:question_id', to: 'entrance_exams#add_question', as: 'add_question_to_entrance_exam'
    delete 'remove_question/:question_id', to: 'entrance_exams#remove_question', as: 'remove_question_from_entrance_exam'
  end

  get 'tags/:tag', to: 'questions#index_formulator', as: :tag
  get '/questions/index_operator', to: 'questions#index_operator'
  get '/questions/index_formulator', to: 'questions#index_formulator'
  get '/questions/index_reviewer', to: 'questions#index_reviewer'
  get '/questions/edit_formulator', to: 'questions#edit_formulator', as: 'question_formulator'
  get '/questions/edit_reviewer', to: 'questions#edit_reviewer', as: 'edit_reviewer'
  get '/questions/formulator_status', to: 'questions#formulator_status', as: 'formulator_status'
  get '/questions/reviewer_status', to: 'questions#reviewer_status', as: 'reviewer_status'
  resources :questions do
    resources :comments, only: %i[index show create update destroy]
    post :assign_question, on: :member
    post :approve_question, on: :member
    post :reject_question, on: :member
    post :send_question_to_review, on: :member
    post :observe_question, on: :member
  end
  get '/users/pertinency_reviewers', to: 'users#pertinency_reviewers'
  get '/users/format_reviewers', to: 'users#format_reviewers'
  resources :users do
    patch :update_password, on: :member
    get :password_edit, on: :member
  end
  resources :roles
  root to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :category_specialities
  has_many :specialities, through: :category_specialities
  has_many :questions
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id'

  def as_fancytree_json
    {
      key: id,
      title: name,
      category_id: id,
      parent_id: parent_id
    }
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

##
# Gestión de categorías.
class CategoriesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[update create destroy]
  before_action :authenticate_user!
  before_action :set_category, only: %i[update destroy]

  ##
  # Retorna la lista de categorías.
  def list
    @categories = Category.where(level: 0)
                          .includes(
                            subcategories: { subcategories: { subcategories: :subcategories } }
                          ).order(:name)

    authorize @categories
  end

  ##
  # Redirige a la vista de edición de categorías.
  def edit_tree
    authorize current_user, policy_class: CategoryPolicy
  end

  # GET /categories
  # GET /categories.json
  ##
  # Redirige a la vista de categorías.
  def index
    authorize current_user, policy_class: CategoryPolicy
  end

  # GET /categories/1
  # GET /categories/1.json
  # def show; end

  # GET /categories/new
  # def new
  #   @category = Category.new
  # end

  # GET /categories/1/edit
  # def edit; end

  # POST /categories
  # POST /categories.json

  ##
  # Crea una categoría nueva.
  def create
    authorize current_user
    parent = Category.where(id: params[:parent_id]).first
    category = Category.new(new_category_params)
    category.is_leaf = true
    parent.is_leaf = false if parent

    respond_to do |format|
      if category.save
        parent&.save
        format.json { render json: category.as_fancytree_json, status: :ok }
      else
        format.json { render json: category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json

  ##
  # Actualiza una categoría.
  def update
    authorize @category
    respond_to do |format|
      if @category.update(category_params)
        format.json { render json: @category.as_fancytree_json, status: :ok }
      else
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json

  ##
  # Elimina una categoría.
  def destroy
    authorize @category
    question = Question.where(category_id: @category.id).first
    if !@category.is_leaf || question
      respond_to do |format|
        format.json do
          render json:
          { error: 'Solo puede eliminar categorías finales sobre las que no se hayan formulado preguntas' },
                 status: :unprocessable_entity
        end
      end
      return
    end

    if @category.destroy
      @category&.parent&.update(is_leaf: true)
      respond_to do |format|
        format.json { render json: @category.as_fancytree_json, status: :ok }
      end
    else
      respond_to do |format|
        format.json { render json: { error: 'No se pudo eliminar la pregunta.' }, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  ##
  # Establece una categoría para ser usada en el controlador.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  ##
  # Retorna parámetros sanitizados para categorías.
  def category_params
    params.permit(:name, :parent_id)
  end

  ##
  # Retorna parámetros sanitizados para categorías.
  def new_category_params
    params.permit(:name, :parent_id, :level)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  def users_attached?(category)
    UserCategory.where(category_id: category.id).present?
  end
end

app/views/categories/_form.html.haml
.container-categories
  = form_with(model: category, local: true) do |form|
    - if category.errors.any?
      #error_explanation
        %h2
          = pluralize(category.errors.count, "error")
          prohibited this category from being saved:
        %ul
          - category.errors.full_messages.each do |message|
            %li= message
    .form-group
      %h5 Ingrese la Categoria y Subcategorias
      #tree
      %p
      %button#button1{:type => "button", class: "btn btn-primary"} Añadir Subcategoria
      %button#button2{:type => "button", class: "btn btn-danger"} Eliminar
      %p
      .actions{style: "float: right"}
        = link_to 'Cancelar', categories_path, class: "btn btn-dark"
      %button#button3{:type => "button", class: "btn btn-primary", style: "float: right"} Guardar

app/views/categories/edit.html.haml
.container-categories
  %h2 Editar Categoria
  = render 'form', category: @category

app/views/categories/edit_tree.html.haml
= javascript_pack_tag 'categories_edit', 'data-turbolinks': 'reload'

.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Administración de Categorías
    .col-md-6.d-flex.right-panel
      = link_to categories_path, class: "btn btn-primary add-button", data: {turbolinks: false} do
        %span{class: "material-icons"} keyboard_return
        Regresar

  .row
    .col-lg-2.col-md-3
      %button.btn.btn-primary.button-categories#blur_tree_button
        Desenfocar
        %span{class: "material-icons"} location_disabled
      %button.btn.btn-primary.button-categories#add_tree_node_button 
        Agregar Nodo Raíz
        %span{class: "material-icons"} library_add
      %button.btn.btn-primary.button-categories#add_node_button
        Agregar Nodo
        %span{class: "material-icons"} add_box
      %button.btn.btn-primary.button-categories#remove_node_button
        Eliminar Nodo
        %span{class: "material-icons"} delete
    .col-lg-10.col-md-9
      #edit_categories_tree

app/views/categories/index.html.haml
= javascript_pack_tag 'categories_index', 'data-turbolinks': 'reload'

.container-questions
  .row.content-header
    .col-md-6
      %h2
        %b Administración de Categorías
    .col-md-6.d-flex.right-panel
      = link_to categories_edit_tree_path, class: "btn btn-primary add-button", data: {turbolinks: false} do
        %span{class: "material-icons"} edit
        Editar Árbol de Categorias

  #index_categories_tree

app/views/categories/new.html.haml
.border
  .container-roles
    %h2 Crear Nueva Categoria
    = render 'form', category: @category
    %br/
    %br/

app/views/categories/show.html.haml
.container-categories
  %h2
    Detalle de Categoria #{@category.name}
  %p
  .form-group
    %label
      %strong Nombre:
    %br/
    %input.form-control.form-control-sm{:readonly => "readonly", style: "height: 40px", type: "text", value: "#{@category.name}"}/
  .float-right
    = link_to 'Editar', edit_category_path(@category), class: "btn btn-primary"
    = link_to 'Regresar', categories_path, class: "btn btn-dark"